# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-16 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderTicket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
