# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-16 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderTicket', '0002_seat_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.IntegerField(default=-1),
        ),
    ]
