# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-16 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderTicket', '0003_auto_20161016_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
