# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-16 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderTicket', '0004_auto_20161016_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(max_length=10),
        ),
    ]
